
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create directory
        run: mkdir temp
      - name: Create directory
        run: ls -al
      - name: Check variables and secrets
        run: | 
          echo ${{vars.FOO}}
          echo ${{secrets.BAR}}

  check-directory:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - name: Check directory
        run: ls -al

  sum-actions:
    runs-on: ubuntu-latest
    steps:
      - id: sum-id
        uses: otokazu-okumura/sum@main
        with:
          x: 10
          y: 5
      - name: result
        run: | 
          echo "sum result is ${{steps.sum-id.outputs.sum-result}}"

  minus-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: minus-id
        uses: ./.github/actions/minus
        with:
          x: 10
          y: 5
      - name: result
        run: |
          echo "minus result is ${{steps.minus-id.outputs.minus-result}}"

  backend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            demo/*.gradle*
            demo/**/gradle-wrapper.properties
      - run: ./gradlew build --no-daemon -i
        working-directory: demo
