
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create directory
        run: mkdir temp
      - name: Create directory
        run: ls -al

  check-directory:
    runs-on: ubuntu-latest
    steps:
      - users: actions/checkout@v4
      - name: Check directory
        runs: ls -al